### ISSUE TITLE
rm CBinding dependency?

### ISSUE THREAD

**Issue by stevengj** [Suavesito-Olimpiada/LibTeXPrintf.jl#10] opened 2023-05-22 12:06 UTC
The upstream API is tiny, just a few functions, no data structures.  It might be worthwhile just calling `@cfunction` directly and removing the CBinding.jl dependency.

(CBinding.jl is a big dependency, especially because it pulls in `Clang_jll`.  Note that it also currently fails to install on nightly because it requires an LLVM  version incompatible with the nightly build.)

**Comment by stevengj** [comment] 2023-05-22 14:45
Also, I suspect that we might as well simplify the API — it's not clear to me that, in Julia, we need to support the full `printf` functionality, since there are already plenty of libraries for that, nor will users want to print to C `stdout` since printing to an IO stream is so much more flexible.   All we really need is a function to take a string and format the equations in it, returning another string?

This would also eliminate the need to call C varargs functions, which are pretty tricky to do correctly.

**Comment by Suavesito-Olimpiada** [comment] 2023-05-22 18:51
The only reason CBinding is there is because of the vararg functions, which I tried to do originally and desisted.

About the rest, capturing stdout and the printing from Julia side has a lot of problems. I got into a non-reproducible bug where some text (that should have been printed by the library) would be kept until the Julia session finished and then was printed.

**Comment by stevengj** [comment] 2023-05-22 19:58
If you only wrap the `sprintf` with no varargs (i.e. disallow `%x`), then both of those problems go away.

> I got into a non-reproducible bug where some text (that should have been printed by the library) would be kept until the Julia session finished and then was printed.

(Probably just a missing `fflush`?)

**Comment by Suavesito-Olimpiada** [comment] 2023-05-22 20:39
Yup, `sprintf` is enough. For eliminating `"%s"` I was thinking to escape the `'%'`. I think is enough with `replace(formatstr, r"%" => "%%")`, for what I see in [`printf`](https://en.cppreference.com/w/c/io/fprintf).

(Maybe, but the library doesn't have a `texfflush()` function and doing `Base.Libc.flush_cstdio()` doesn't fix it. The full error is that sometimes when trying to capture text
— part of the text is printed,
— none of it is captured, 
— I can continue using the session, but,
— once I close it, the rest of the text is printed.
Perhaps the library and Julia are not linked to the same libc? I don't think so, but I honestly have no idea of what is happening here.)

**Closed as completed** 2023-06-05 04:29 UTC
